package exceptions;

public class _2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			int a = 10/0;
			
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("we cannot divide a number with zero");
		}
		

	}

}
